--Criando banco de dados
CREATE DATABASE DungeonsNdragons
go

USE DungeonsNdragons
go

CREATE TABLE RACA(
			ID INT IDENTITY(1,1),
			DESCRICAO NVARCHAR(30) NOT NULL,
			BONUS NVARCHAR(300) NOT NULL,
			CONSTRAINT PK_RACA PRIMARY KEY(ID)			
			);
GO

CREATE TABLE DIVINDADE(
			ID INT IDENTITY(1,1),
			NOME NVARCHAR(30) NOT NULL,
			DOMINIO NVARCHAR(30) NOT NULL
			CONSTRAINT PK_DIVINDADE PRIMARY KEY(ID)			
			);

CREATE TABLE CLASSE(
			ID INT IDENTITY(1,1),
			DESCRICAO NVARCHAR(30) NOT NULL,
			"LEVEL" INT DEFAULT 1 NOT NULL,
			XP INT NOT NULL,
			CONSTRAINT PK_CLASSE PRIMARY KEY(ID)			
			);
GO

CREATE TABLE SUB_CLASSE(
			ID INT IDENTITY(1,1),
			ID_CLASSE INT NOT NULL,
			CONSTRAINT PK_SUB_CLASSE PRIMARY KEY(ID),
			CONSTRAINT FK_SUB_CLASSE_CLASSE FOREIGN KEY(ID_CLASSE) REFERENCES CLASSE(ID)
			);
GO

CREATE TABLE PERSONAGEM(
			ID INT IDENTITY(1,1),
			NOME NVARCHAR(50) NOT NULL,
			PESO FLOAT NOT NULL,
			ALTURA FLOAT NOT NULL,
			SEXO NVARCHAR(8) NOT NULL,
			MORALIDADE NVARCHAR(30) NOT NULL,
			ID_DIVINDADE INT,
			ID_RACA INT NOT NULL,
			ID_CLASSE INT,
			ID_SUBCLASSE INT,
			CONSTRAINT PK_PERSONAGEM PRIMARY KEY(ID),
			CONSTRAINT FK_PERSONAGEM_DIVINDADE FOREIGN KEY(ID_DIVINDADE) REFERENCES DIVINDADE(ID),
			CONSTRAINT FK_PERSONAGEM_RACA FOREIGN KEY(ID_RACA) REFERENCES RACA(ID),
			CONSTRAINT FK_PERSONAGEM_CLASSE FOREIGN KEY(ID_CLASSE) REFERENCES CLASSE(ID),
			CONSTRAINT FK_PERSONAGEM_SUBCLASSE FOREIGN KEY(ID_SUBCLASSE) REFERENCES SUB_CLASSE(ID),
			);
GO



